/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design System Colors (from design HTML)
        "outline-variant": "#414752",
        "on-error-container": "#ffdad6",
        "surface-tint": "#a2c9ff",
        "primary-fixed": "#d3e4ff",
        "primary-container": "#58a6ff",
        outline: "#8b919d",
        "surface-dim": "#101419",
        "surface-variant": "#32353b",
        "surface-container-lowest": "#0b0e14",
        "on-primary-fixed": "#001c38",
        "inverse-on-surface": "#2d3136",
        "inverse-surface": "#e0e2ea",
        "on-primary-container": "#003a6b",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004882",
        "on-tertiary-fixed-variant": "#614000",
        "on-secondary-container": "#b0b5be",
        "tertiary-fixed": "#ffddaf",
        "surface-container": "#1c2025",
        "surface-container-high": "#272a30",
        "on-tertiary-fixed": "#281800",
        "on-tertiary": "#432c00",
        "surface-container-low": "#181c21",
        "on-secondary": "#2b3138",
        "secondary-fixed-dim": "#c1c7d0",
        error: "#ffb4ab",
        "on-tertiary-container": "#4f3400",
        "on-background": "#e0e2ea",
        secondary: "#c1c7d0",
        "on-secondary-fixed": "#161c23",
        "secondary-fixed": "#dde3ec",
        "on-surface-variant": "#c0c7d4",
        surface: "#101419",
        primary: "#a2c9ff",
        background: "#101419",
        "primary-fixed-dim": "#a2c9ff",
        "on-surface": "#e0e2ea",
        "surface-bright": "#36393f",
        "inverse-primary": "#0060aa",
        "on-error": "#690005",
        "tertiary-container": "#da9600",
        "on-primary": "#00315c",
        tertiary: "#ffba42",
        "tertiary-fixed-dim": "#ffba42",
        "on-secondary-fixed-variant": "#41474f",
        "secondary-container": "#41474f",
        "surface-container-highest": "#32353b",

        // Semantic method colors
        "method-get-bg": "#1e4620",
        "method-get-text": "#a5d6a7",
        "method-get-border": "#2e7d32",
        "method-post-bg": "#32353b", // surface-variant
        "method-post-text": "#c0c7d4", // on-surface-variant
        "method-post-border": "#414752", // outline-variant
        "method-put-bg": "#4a148c",
        "method-put-text": "#ce93d8",
        "method-put-border": "#7b1fa2",
        "method-delete-bg": "#b71c1c",
        "method-delete-text": "#ffcdd2",
        "method-delete-border": "#c62828",

        // Success/Error colors
        success: "#a5d6a7",
        "success-bg": "#1e4620",
        "success-border": "#2e7d32",
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "700",
          },
        ],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      // spacing: {
      //   base: "4px",
      //   lg: "24px",
      //   xl: "48px",
      //   xs: "4px",
      //   md: "16px",
      //   sm: "8px",
      //   gutter: "16px",
      //   "container-max": "1440px",
      // },
      boxShadow: {
        "active-glow": "0 0 8px rgba(162, 201, 255, 0.15)",
        "active-glow-hover": "0 0 12px rgba(162, 201, 255, 0.25)",
        "error-glow": "0 0 12px rgba(147, 0, 10, 0.3)",
        "success-glow": "0 0 10px rgba(46, 125, 50, 0.3)",
        "success-glow-hover": "0 0 15px rgba(46, 125, 50, 0.5)",
      },
    },
  },
  plugins: [],
}